<option value="New York">New York</option>
<option value="Los Angeles">Los Angeles</option>
<option value="Chicago">Chicago</option>
<option value="Houston">Houston</option>
<option value="Phoenix">Phoenix</option>
<option value="Philadelphia">Philadelphia</option>
<option value="San Antonio">San Antonio</option>
<option value="San Diego">San Diego</option>
<option value="Dallas">Dallas</option>
<option value="Austin">Austin</option>
<option value="San Jose">San Jose</option>
<option value="Fort Worth">Fort Worth</option>
<option value="Jacksonville">Jacksonville</option>
<option value="Columbus">Columbus</option>
<option value="Charlotte">Charlotte</option>
<option value="Indianapolis">Indianapolis</option>
<option value="Seattle">Seattle</option>
<option value="Denver">Denver</option>
<option value="Washington">Washington</option>
<option value="Boston">Boston</option>
<option value="Nashville">Nashville</option>
<option value="Baltimore">Baltimore</option>
<option value="Oklahoma City">Oklahoma City</option>
<option value="Portland">Portland</option>
<option value="Las Vegas">Las Vegas</option>
<option value="Detroit">Detroit</option>
<option value="Memphis">Memphis</option>
<option value="Louisville">Louisville</option>
<option value="Milwaukee">Milwaukee</option>
<option value="Albuquerque">Albuquerque</option>
<option value="Toronto">Toronto</option>
<option value="Vancouver">Vancouver</option>
<option value="Montreal">Montreal</option>
<option value="Calgary">Calgary</option>
<option value="Edmonton">Edmonton</option>
<option value="Ottawa">Ottawa</option>
<option value="Mexico City">Mexico City</option>
<option value="Guadalajara">Guadalajara</option>
<option value="Monterrey">Monterrey</option>
<option value="Cancun">Cancun</option>

<option value="Sao Paulo">Sao Paulo</option>
<option value="Rio de Janeiro">Rio de Janeiro</option>
<option value="Brasilia">Brasilia</option>
<option value="Salvador">Salvador</option>
<option value="Fortaleza">Fortaleza</option>
<option value="Belo Horizonte">Belo Horizonte</option>
<option value="Buenos Aires">Buenos Aires</option>
<option value="Bogota">Bogota</option>
<option value="Lima">Lima</option>
<option value="Santiago">Santiago</option>
<option value="Caracas">Caracas</option>
<option value="Quito">Quito</option>
<option value="Montevideo">Montevideo</option>
<option value="Asuncion">Asuncion</option>
<option value="La Paz">La Paz</option>
<option value="Medellin">Medellin</option>
<option value="Cali">Cali</option>
<option value="Guayaquil">Guayaquil</option>

<option value="London">London</option>
<option value="Manchester">Manchester</option>
<option value="Birmingham">Birmingham</option>
<option value="Liverpool">Liverpool</option>
<option value="Paris">Paris</option>
<option value="Marseille">Marseille</option>
<option value="Lyon">Lyon</option>
<option value="Berlin">Berlin</option>
<option value="Munich">Munich</option>
<option value="Hamburg">Hamburg</option>
<option value="Frankfurt">Frankfurt</option>
<option value="Madrid">Madrid</option>
<option value="Barcelona">Barcelona</option>
<option value="Valencia">Valencia</option>
<option value="Seville">Seville</option>
<option value="Rome">Rome</option>
<option value="Milan">Milan</option>
<option value="Naples">Naples</option>
<option value="Venice">Venice</option>
<option value="Florence">Florence</option>
<option value="Amsterdam">Amsterdam</option>
<option value="Rotterdam">Rotterdam</option>
<option value="Brussels">Brussels</option>
<option value="Antwerp">Antwerp</option>
<option value="Vienna">Vienna</option>
<option value="Salzburg">Salzburg</option>
<option value="Zurich">Zurich</option>
<option value="Geneva">Geneva</option>
<option value="Dublin">Dublin</option>
<option value="Cork">Cork</option>
<option value="Lisbon">Lisbon</option>
<option value="Porto">Porto</option>
<option value="Athens">Athens</option>
<option value="Thessaloniki">Thessaloniki</option>
<option value="Stockholm">Stockholm</option>
<option value="Gothenburg">Gothenburg</option>
<option value="Oslo">Oslo</option>
<option value="Bergen">Bergen</option>
<option value="Copenhagen">Copenhagen</option>
<option value="Helsinki">Helsinki</option>
<option value="Warsaw">Warsaw</option>
<option value="Krakow">Krakow</option>
<option value="Prague">Prague</option>
<option value="Budapest">Budapest</option>
<option value="Bucharest">Bucharest</option>
<option value="Sofia">Sofia</option>
<option value="Belgrade">Belgrade</option>
<option value="Zagreb">Zagreb</option>
<option value="Istanbul">Istanbul</option>
<option value="Moscow">Moscow</option>
<option value="Saint Petersburg">Saint Petersburg</option>
<option value="Kyiv">Kyiv</option>

<option value="Tokyo">Tokyo</option>
<option value="Osaka">Osaka</option>
<option value="Kyoto">Kyoto</option>
<option value="Yokohama">Yokohama</option>
<option value="Nagoya">Nagoya</option>
<option value="Seoul">Seoul</option>
<option value="Busan">Busan</option>
<option value="Incheon">Incheon</option>
<option value="Beijing">Beijing</option>
<option value="Shanghai">Shanghai</option>
<option value="Guangzhou">Guangzhou</option>
<option value="Shenzhen">Shenzhen</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Macau">Macau</option>
<option value="Chengdu">Chengdu</option>
<option value="Wuhan">Wuhan</option>
<option value="Mumbai">Mumbai</option>
<option value="Delhi">Delhi</option>
<option value="Bangalore">Bangalore</option>
<option value="Hyderabad">Hyderabad</option>
<option value="Chennai">Chennai</option>
<option value="Kolkata">Kolkata</option>
<option value="Ahmedabad">Ahmedabad</option>
<option value="Pune">Pune</option>
<option value="Bangkok">Bangkok</option>
<option value="Phuket">Phuket</option>
<option value="Chiang Mai">Chiang Mai</option>
<option value="Singapore">Singapore</option>
<option value="Kuala Lumpur">Kuala Lumpur</option>
<option value="Penang">Penang</option>
<option value="Jakarta">Jakarta</option>
<option value="Bali">Bali</option>
<option value="Manila">Manila</option>
<option value="Cebu">Cebu</option>
<option value="Ho Chi Minh City">Ho Chi Minh City</option>
<option value="Hanoi">Hanoi</option>
<option value="Yangon">Yangon</option>
<option value="Dhaka">Dhaka</option>
<option value="Lahore">Lahore</option>
<option value="Karachi">Karachi</option>
<option value="Islamabad">Islamabad</option>
<option value="Tehran">Tehran</option>
<option value="Baghdad">Baghdad</option>
<option value="Riyadh">Riyadh</option>
<option value="Jeddah">Jeddah</option>
<option value="Mecca">Mecca</option>
<option value="Medina">Medina</option>
<option value="Dubai">Dubai</option>
<option value="Abu Dhabi">Abu Dhabi</option>
<option value="Doha">Doha</option>
<option value="Kuwait City">Kuwait City</option>
<option value="Muscat">Muscat</option>
<option value="Amman">Amman</option>
<option value="Beirut">Beirut</option>
<option value="Tel Aviv">Tel Aviv</option>
<option value="Jerusalem">Jerusalem</option>

<option value="Cairo">Cairo</option>
<option value="Alexandria">Alexandria</option>
<option value="Giza">Giza</option>
<option value="Lagos">Lagos</option>
<option value="Abuja">Abuja</option>
<option value="Nairobi">Nairobi</option>
<option value="Mombasa">Mombasa</option>
<option value="Johannesburg">Johannesburg</option>
<option value="Cape Town">Cape Town</option>
<option value="Durban">Durban</option>
<option value="Pretoria">Pretoria</option>
<option value="Casablanca">Casablanca</option>
<option value="Marrakech">Marrakech</option>
<option value="Rabat">Rabat</option>
<option value="Tunis">Tunis</option>
<option value="Algiers">Algiers</option>
<option value="Accra">Accra</option>
<option value="Kumasi">Kumasi</option>
<option value="Dakar">Dakar</option>
<option value="Addis Ababa">Addis Ababa</option>
<option value="Khartoum">Khartoum</option>
<option value="Kampala">Kampala</option>
<option value="Dar es Salaam">Dar es Salaam</option>
<option value="Luanda">Luanda</option>
<option value="Maputo">Maputo</option>
<option value="Harare">Harare</option>
<option value="Lusaka">Lusaka</option>
<option value="Kigali">Kigali</option>
<option value="Antananarivo">Antananarivo</option>
<option value="Sydney">Sydney</option>
<option value="Melbourne">Melbourne</option>
<option value="Brisbane">Brisbane</option>
<option value="Perth">Perth</option>
<option value="Adelaide">Adelaide</option>
<option value="Canberra">Canberra</option>
<option value="Gold Coast">Gold Coast</option>
<option value="Newcastle">Newcastle</option>
<option value="Auckland">Auckland</option>
<option value="Wellington">Wellington</option>
<option value="Christchurch">Christchurch</option>
<option value="Hamilton">Hamilton</option>
<option value="Suva">Suva</option>
<option value="Port Moresby">Port Moresby</option>
<option value="Dubai">Dubai</option>
<option value="Abu Dhabi">Abu Dhabi</option>
<option value="Sharjah">Sharjah</option>
<option value="Doha">Doha</option>
<option value="Kuwait City">Kuwait City</option>
<option value="Manama">Manama</option>
<option value="Muscat">Muscat</option>
<option value="Riyadh">Riyadh</option>
<option value="Jeddah">Jeddah</option>
<option value="Mecca">Mecca</option>
<option value="Medina">Medina</option>
<option value="Amman">Amman</option>
<option value="Beirut">Beirut</option>
<option value="Tel Aviv">Tel Aviv</option>
<option value="Jerusalem">Jerusalem</option>
<option value="Baghdad">Baghdad</option>
<option value="Erbil">Erbil</option>
<option value="Tehran">Tehran</option>
<option value="Isfahan">Isfahan</option>
<option value="Shiraz">Shiraz</option>
<option value="Ankara">Ankara</option>
<option value="Istanbul">Istanbul</option>
<option value="Izmir">Izmir</option>


